# Generated by Django 4.1.2 on 2022-10-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0003_alter_breed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Small', 'Small'), ('Tiny', 'Tiny'), ('Large', 'Large')], default='', max_length=6),
        ),
    ]
