# Generated by Django 4.1.2 on 2022-10-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0011_alter_breed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Tiny', 'Tiny'), ('Small', 'Small')], default='', max_length=6),
        ),
    ]
